services:
  db:
    image: postgres:15
    container_name: dmlab_postgres
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
